# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  node: circleci/node@5.2.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  test:
    docker:
      - image: cimg/node:22.5
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - node/install-packages:
          app-dir: ./my
          pkg-manager: yarn
          check-cache: always
      - run:
          name: build
          command: cd my && yarn build
# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build:
    jobs:
      - test